### ISSUE TITLE
Create Post

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#1]
As a User, I need to create a Post to display my recommendation.

**Description:**
Creating a Post
<img width="371" alt="Bildschirmfoto 2022-03-25 um 15 16 27" src="https://user-images.githubusercontent.com/98757476/160138031-284c1aff-3ae0-4362-b840-cb40ff4aa6eb.png">

**Acceptance Criteria:**

- [x] if input field is empty, the form doesn't send
- [x] Input field has a max length of 150-200 spaces
- [x] on submit a new post is created

 
 
**Tasks**

- [x] create a Form and input field for the content
- [x] create a Button and the onclick function
- [x] Create Test for Button and Input
