### ISSUE TITLE
Categories dropdown menu

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#11]
**Value Preposition**

As a User, I need Categories, to be able to assign the Post to a Category

**Description:**

The Input-field on the Create-Page gets a dropdown menu of Categories. The User has to assign his Post to a Category.

**Acceptance Criteria:**

- [x] If the User creates a post, he has to choose a Category from the dropdown menu
- [x] If the Category is not chosen, the form cant be sent
- [x] The Category will also be displayed on the Post from the User

 
**Tasks**

- [x] add a dropdown menu with different Categories to the Input-field
- [x] setup required to the dropdown menu, so the form can only be sent if a category is chosen
- [x] add the chosen Category to the Users Post
- [x] connect the choosen Category to the Users Post ID
