### ISSUE TITLE
Filter Posts by Category

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#12]
**Value Preposition**

As a User, I can filter the Posts on the Homepage by Categories, to have a better overview of the Post(or Category) I want to see.

**Description:**

Different Categories will be displayed on the Homepage.
The User can filter the Posts by the chosen category.
If a category is selected, only the corresponding posts are displayed.

**Acceptance Criteria:**

- [x] The Homepage displays different Category options
- [x] If the User selects a Category, every Post of this Category will be displayed

 
**Tasks**

- [x] display all Categories on the homepage by mapping them from the Users-Post-database
- [x] onClick the chosen Category will filter out every Post(from the database) it is assigned to
