### ISSUE TITLE
Rate Post

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#13]
**Value Preposition**

As a User, I need a rate function, to be able to rate a Post.

**Description:**

The user sees a rate function (e.g. Like-Button) on the Post-Cards in the feed.
By clicking them or giving them a like or a rating, the like counter will get a +1 count. 

**Acceptance Criteria:**

- [x] There is a rating function on the Post-Card in the feed (e.g. Like-Button)
- [x] If the User likes(rates) the Post (onClick like button), it will display a +1 count for every user next to like/rate button.

 
**Tasks**

- [x] add a like/rate function on the Post-Cards in the feed (Homepage)
- [x] add a counter for every like and display it next to the like button
