### ISSUE TITLE
Bookmark Post

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#14]
**Value Preposition**

As a User, I need a bookmark function, to be able to bookmark a Post.

**Description:**

The user sees a bookmark option/function on the Post-Cards in the feed.
By clicking the bookmark icon, the Post-Card will be bookmarked and displayed on the Profile Page.

**Acceptance Criteria:**

- [x] There is a bookmark function on the Post-Card in the feed (e.g. Like-Button)
- [x] If the User bookmarks a Post by clicking on it, the Post-Card will be added and displayed on the Profile Page

 
**Tasks**

- [x] add a bookmark option on the Post-Cards in the feed (Homepage)
- [ ] onClick the bookmarked Post-Card, will be displayed and added to the Profile Page
