### ISSUE TITLE
seperate Posts on Profile

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#19]
**Value Preposition**

As a User, I need to have a good and separate overview of my own and saved posts.

**Description:**
<img width="893" alt="Bildschirmfoto 2022-04-10 um 14 58 17" src="https://user-images.githubusercontent.com/98757476/162619350-fdb6dfcb-9208-433a-8a44-1d9a55e0d773.png">

**Acceptance Criteria:**

- [x] On top of the Postlist two titles are displayed( My Posts & Bookmarked)
- [x] onClick of the Title the assigned Postlist will be displayed ( own Posts & bookmarked Posts)

 
**Tasks**

- [x] add onclick function to the titles and render assigned the assigned posts
