### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#2]
As a User, I need to click on the Icons in the Navigation to switch between the pages.

**Description:**
Creating a Navigation and the Logic
<img width="652" alt="Bildschirmfoto 2022-03-24 um 15 45 37" src="https://user-images.githubusercontent.com/98757476/159942625-9f66d15d-7b82-40b3-a055-4971df7cb115.png">

**Acceptance Criteria:**

- [x] If an icon is clicked, the page will switch
- [x] clicked or active icon will get a border-top

 
**Tasks**

- [x] create a Navigation with Icons (Home, Create, Profile)
- [x] when Icon is clicked, the icon will get a border-top
