### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#20]
**Value Preposition**

As a User, I need to see a good styling to have a good user experience

**Description:**
The final design:
- style a logo
- style landing page(new background)
- style buttons
- style components
- style details
- responsive design

**Acceptance Criteria:**

- [x] The Landingpage has a new and final background and logo
- [x] buttons and components have the final styling
- [x] details (logo, icons, titles ) are set
- [x] integrated responsive design
 
**Tasks**

- [x] design a logo
- [x] design or find a background img
- [x] design button
- [x] design compononents
- [x] design details
- [x] choose colors and fonts
- [x] integrate media quieres
