### ISSUE TITLE
Display Posts on Home Page

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#3]
As a user, I want to see my post on the Home Page after submitting so other people can read them.

**Description:**
Posts will be displayed on Home Page when the Post Button is clicked
<img width="363" alt="Bildschirmfoto 2022-03-25 um 15 57 27" src="https://user-images.githubusercontent.com/98757476/160146299-6e2446d2-784f-454f-8c1a-33e46b1439d2.png">

**Acceptance Criteria:**

- [x] If Post Button is clicked, the post will be shown on the Home Page

 
**Tasks**

- [x] add Function if Post button is clicked, the post will be shown on the Home Page
- [x] Create Test for the Button
