### ISSUE TITLE
Display own Post on Profile Page

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#5]
As a user, I want to see my post on my Profile Page after submitting to have an overview of my posts

**Description:**
Posts will be displayed on Profile Page when the Post Button is clicked
<img width="362" alt="Bildschirmfoto 2022-03-25 um 15 57 49" src="https://user-images.githubusercontent.com/98757476/160146558-f49f94c0-deb5-4f1a-89f6-67eaaf5ad851.png">

**Acceptance Criteria:**

- [x] If Post Button is clicked, the post will be shown on the Profile Page

 
**Tasks**

- [x] add Function if Post button is clicked, the post will be shown on the Profile Page
- [ ] Create Test for the Button
