### ISSUE TITLE
Log-In

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#7]
**Value Preposition**

As a user, i need a Log in Function to be able to save my data and get access to the data from any device

**Description:**

<img width="390" alt="Bildschirmfoto 2022-03-29 um 15 03 21" src="https://user-images.githubusercontent.com/98757476/160617469-ab6d74c3-4339-496f-a35e-9622e58480a7.png">

**Acceptance Criteria:**

- [x] On the Landing page is a sign in button
- [x] On click it redirects the user to the login options

 
**Tasks**

- [x] create a landing-page
- [x] implement a sign
- [x] style the page
- [x] create a Log in Function with next-auth to get Log In Options (Facebook, Google)
