### ISSUE TITLE
backend/database

### ISSUE THREAD

**Issue by AdeelB91** [AdeelB91/capstone-project#8]
**Value Preposition**

As a User, I need a database, to be able to save (and share) my data (posts) and get access to it from any device.

**Description:**

Every user is getting a unique ID. All of the data (Posts, User- Information) created by the User will be assigned to his ID.

**Acceptance Criteria:**

- [x] If the User creates a post, the data from the post will be assigned to the Unique-UserID object, by clicking the Create Post button.

 
**Tasks**

- [x] create a new project and a collection with MongoDB
- [x] install and setup MongoDB and mongoose in the project
- [x] onClick function, so that the data will be saved (POST)
